# Generated by Django 4.0.2 on 2022-02-19 03:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranlao', '0002_visitorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitorlog',
            name='amount',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
